# Configurações de conexão ao banco de dados
flyway.url=${DATABASE_URL}
flyway.user=${DATABASE_USER}
flyway.password=${DATABASE_PASSWORD}

# Define o schema a ser utilizado
flyway.schemas=accountms
flyway.defaultSchema=accountms

# Diretório onde as migrations SQL estão localizadas
flyway.locations=classpath:db/migration

# Define o comportamento em produção
flyway.baselineOnMigrate=true
flyway.cleanDisabled=true

# Outras configurações úteis
flyway.sqlMigrationSuffixes=.sql
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.table=flyway_schema_history
