services:
  grafana:
    # Grafana - Analytics & monitoring visualization
    image: grafana/grafana:11.2.1
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    ports:
      - "4317:4317"  # gRPC port
      - "4318:4318"  # HTTP port
    network_mode: "host"

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.1
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # - ./logs/account-microservice/:/usr/share/filebeat/logs:ro --Se estiver rodando em um container
      - "${LOG_PATH}:/usr/share/filebeat/logs:ro"
    command: filebeat -e --strict.perms=false
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # Configura o Elasticsearch para rodar em modo de nó único.
      - xpack.security.enabled=false  # Desabilita a segurança para simplificar (não recomendado para produção)
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data # Persiste os dados do Elasticsearch em um volume Docker.
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  postgresql:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  grafana-storage:
  # Volume para Grafana

  postgres-data:
  # Volume para PostgreSQL

  elasticsearch-data:
  # Volume para ElasticSearch
